# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='photoURLString',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
