# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171027_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='photoURLString',
            field=models.CharField(max_length=1000),
        ),
    ]
